spring:
  #redis 配置
  redis:
    database: 0
    cluster:
      nodes: 192.168.0.28:6379,192.168.0.28:6380,192.168.0.28:6381,192.168.0.28:6382,192.168.0.28:6383,192.168.0.28:6384
      max-redirects: 3
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password:
jeecg:
  xxljob:
    enabled: true
    adminAddresses: http://192.168.0.28:9080/xxl-job-admin
    appname: ${spring.application.name}
    accessToken: ''
    address: 127.0.0.1:30008
    ip: 127.0.0.1
    port: 30008
    logPath: logs/job/jobhandler/
    logRetentionDays: 30